### ISSUE TITLE
Is there a plan to make this package compatible with the new pricing plans of the Twitter API?

### ISSUE THREAD

**Issue by K9i-0** [0maru/twitter_login#117]
It seems that the endpoints used internally by this package could be affected by the new pricing plans of the Twitter API.
https://developer.twitter.com/en

The v1.1 endpoints used in the login method will no longer be available in the Free and Basic plans.
https://github.com/0maru/twitter_login/blob/main/lib/src/utils.dart#L17-L19

The /2/users/:id endpoint used in the loginV2 method will no longer be available in the Free plan.
https://github.com/0maru/twitter_login/blob/main/lib/src/utils.dart#L21

**Comment by mohamedali170** [comment]
It's working normally for now.

**Comment by K9i-0** [comment]
It seems that the changes will be made after April 30th.

https://twitter.com/TwitterDev/status/1641222786894135296?s=20

**Comment by 0maru** [comment]
Yes, I do.
It is scheduled to be implemented this weekend.

**Comment by 0maru** [comment]
v4.3.2 released.

No major changes have been made because user data can still be obtained with the free and basic plans.
Rate limits are set for each user, and error handling has been added to handle requests that exceed the rate limit.

|Versino|Endpoint|Rate Limit|
|---|---|---|
|v1.1|GET /2/users/me|25 requests / 24 hours / PER USER|
|v2|GET /2/users|100 requests / 24 hours / PER USER|

**Comment by K9i-0** [comment]
Thank you very much.😄
