### ISSUE TITLE
Firebase Auth Handle is not working

### ISSUE THREAD

**Issue by arslanrazacrew** [0maru/twitter_login#120]
I'm using the below URL to redirect but this isn't working.  Giving me error 
'Unable to process the request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.'

https://<Appname>.firebaseapp.com/__/auth/handler

**Comment by Julitech** [comment]
I am using this directly from Firebase and have no issues

`TwitterAuthProvider twitterProvider = TwitterAuthProvider();
        userCredential = await _auth.signInWithProvider(twitterProvider);`

**Comment by 0maru** [comment]
@arslanrazacrew 
Sorry it took so long.

This plugin launches a browser, but it is not running on `xxx.firebaseapp.com` domain, so there is no session where the `xxx.firebaseapp.com` page is accessible.

I have verified this in my environment and it does not work with `xxx.firebaseapp.com/__/auth/handler`.
If the firebase domain is available, it works if you configure it to redirect to another page instead of `xxx.firebaseapp.com`.
