### ISSUE TITLE
Change the old Twitter logo

### ISSUE THREAD

**Issue by ilyasarafathemvigo** [0maru/twitter_login#129]
## Bug report

**Describe the bug**

---

## Additional context
![Screenshot_1692252996](https://github.com/0maru/twitter_login/assets/121234451/5e1883ca-e4b1-4028-a7ca-2a2e2dc705f8)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Which method do you use?

- [&#10003;  ] login()

- [ ] loginV2()

**Comment by nayanAubie** [comment]
@ilyasarafathemvigo FYI, this is not a part of this plugin, it's a Chrome tab and it can be changed by the Twitter team itself.

**Comment by git00000000001** [comment]
Can you successfully authenticate and log in to Twitter? Why do I keep encountering this problem?

Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared. Some specific scenarios are - 1) Using IDP-Initiated SAML SSO. 2) Using signInWithRedirect in a storage-partitioned browser environmen
