### ISSUE TITLE
Feature request: logout

### ISSUE THREAD

**Issue by Just66** [0maru/twitter_login#5]
Seems that this one is missing logout, so user may login with another twitter account, isn't that?

**Comment by 0maru** [comment]
This plugin is not use the TwitterSDK, instead of uses TwitterOAuth.
Twitter OAuth is uses session.
The session with Twitter is defined by a cookie owned by Twitter.

Therefore, I can't implement a logout process, but we have added "force_login" to force the login form to appear.
"force_login" can be used to switch between Twitter accounts.


for example
```
final twitterLogin = TwitterLogin(...);
twitterLogin.login(forceLogin: true);
```
