### ISSUE TITLE
Allow auth with oauth 2.0

### ISSUE THREAD

**Issue by Fnalsk** [0maru/twitter_login#85]
Currently the example usage shows that you need an `apiKey` and `apiSecretKey` to use this package. However this is only relevant for oauth 1.0a as per the twitter auth docs:

https://developer.twitter.com/en/docs/authentication/overview

oauth 2.0 allows for more control over the scope of requested permissions. For example, I only need users' permission to create tweets, which I could request separately through OAuth 2.0. But if I want to use this package I can only use OAuth 1.0a, which means I would have to ask the user for about 10 other permissions that I don't need.

**Comment by myConsciousness** [comment]
Hi is this thread still alive?

I'm developing a library for Twitter API v2.0 and I want to recommend this library if it's possible to support OAuth 2.0 PKCE.

https://pub.dev/packages/twitter_api_v2

**Comment by 0maru** [comment]
This plugin is third-party login with Twitter plugin.
Using the loginV2 method, OAuth 2.0 can be used.
However, this plugin doesn't control to request permissions.


@myConsciousness 
thank you.
But I don't think twitter_api_v2 has not twitter login method.

**Comment by myConsciousness** [comment]
Hi @0maru ,

`twitter_api_v2` is just a wrapper for Twitter API v2.0 so of course it doesn't support login method. I was hoping to cover OAuth2 PKCE with [twitter_login](https://github.com/0maru/twitter_login), but it looks like I will have to implement it myself.

Best,
Shinya

**Comment by 0maru** [comment]
@myConsciousness 
I was going for a lightweight plugin that only provides login functionality.
However, I could't imagine using it in combination with `twitter_api_v2`.

I will try to implement it so that the scope can be selected.
Is it sufficient for twitter_api_v2 to select [OAuth 2.0 Authorization Code with PKCE Scopes](https://developer.twitter.com/en/docs/authentication/guides/v2-authentication-mapping)?

thanks.
